# Generated by Django 6.0 on 2026-02-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_helprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='admin_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
