# Generated by Django 6.0 on 2026-02-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_helprequest_admin_reply_helprequest_replied_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverablePincode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='is_deliverable',
            field=models.BooleanField(default=False),
        ),
    ]
