# Generated by Django 6.0 on 2026-02-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_deliverablepincode_address_is_deliverable'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverablepincode',
            name='city',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliverablepincode',
            name='pincode',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
