# Generated by Django 6.0 on 2026-02-06 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_order_otp_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_otp',
        ),
        migrations.RemoveField(
            model_name='order',
            name='otp_created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='otp_verified',
        ),
        migrations.AlterField(
            model_name='deliverablepincode',
            name='city',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='DeliveryOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_otp', to='api.order')),
            ],
        ),
    ]
